branch-defaults:
  master:
    environment: null
    group_suffix: null

  deploy: 
    artifact: ./www/Archive.zip
  n:
    environment: image-filter-microservice-dev
global:
  application_name: image-filter-microservice
  branch: null
  default_ec2_keyname: ukey
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
